%{init: {"theme": "default"}}%
flowchart LR
    % Module: github.com/SoundMatt/go-CAN
    % Generated: 2026-06-19T13:23:00Z

    github_com_SoundMatt_go_CAN["can"]
    github_com_SoundMatt_go_CAN_cmd_cantool["github.com/SoundMatt/go-CAN/cmd/cantool"]
    github_com_SoundMatt_go_CAN_dbc["dbc"]
    github_com_SoundMatt_go_CAN_examples_quickstart["github.com/SoundMatt/go-CAN/examples/quickstart"]
    github_com_SoundMatt_go_CAN_examples_quickstart_receiver["github.com/SoundMatt/go-CAN/examples/quickstart/receiver"]
    github_com_SoundMatt_go_CAN_examples_quickstart_sender["github.com/SoundMatt/go-CAN/examples/quickstart/sender"]
    github_com_SoundMatt_go_CAN_isotp["isotp"]
    github_com_SoundMatt_go_CAN_j1939["j1939"]
    github_com_SoundMatt_go_CAN_mock["mock"]
    github_com_SoundMatt_go_CAN_obdii["obdii"]
    github_com_SoundMatt_go_CAN_recorder["recorder"]
    github_com_SoundMatt_go_CAN_safety["safety"]
    github_com_SoundMatt_go_CAN_socketcan["socketcan"]
    github_com_SoundMatt_go_CAN_uds["uds"]
    github_com_SoundMatt_go_CAN_virtual["virtual"]

    github_com_SoundMatt_go_CAN_cmd_cantool --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_cmd_cantool --> github_com_SoundMatt_go_CAN_recorder
    github_com_SoundMatt_go_CAN_cmd_cantool --> github_com_SoundMatt_go_CAN_socketcan
    github_com_SoundMatt_go_CAN_cmd_cantool --> github_com_SoundMatt_go_CAN_virtual
    github_com_SoundMatt_go_CAN_examples_quickstart --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_examples_quickstart --> github_com_SoundMatt_go_CAN_virtual
    github_com_SoundMatt_go_CAN_examples_quickstart_receiver --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_examples_quickstart_receiver --> github_com_SoundMatt_go_CAN_virtual
    github_com_SoundMatt_go_CAN_examples_quickstart_sender --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_examples_quickstart_sender --> github_com_SoundMatt_go_CAN_virtual
    github_com_SoundMatt_go_CAN_isotp --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_j1939 --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_mock --> github_com_SoundMatt_go_CAN_virtual
    github_com_SoundMatt_go_CAN_obdii --> github_com_SoundMatt_go_CAN_isotp
    github_com_SoundMatt_go_CAN_recorder --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_socketcan --> github_com_SoundMatt_go_CAN
    github_com_SoundMatt_go_CAN_uds --> github_com_SoundMatt_go_CAN_isotp
    github_com_SoundMatt_go_CAN_virtual --> github_com_SoundMatt_go_CAN
